### ISSUE TITLE
Using "plain" encoding for program source does not seem to work

### ISSUE THREAD

**Issue by BjrInt** [aleph-im/aleph-vm#478]
# Problem description

Creating a VM with a program source sent as a "plain" encoded file does not seem to work. 

## How to reproduce :

Create two program with the exact same source. For one of the program use "zip" or "squashfs" encoding, and for the other "plain". The one with the plain encoding will fail, and an HTTP 500 error will be issued.

# Additional reference

https://github.com/aleph-im/front-aleph-cloud-page/pull/76

**Comment by hoh** [comment]
The entrypoint provided by the web console was invalid, hence causing the issue. Nothing to fix on the backend.
