### ISSUE TITLE
Upgrade to  Firecracker v1.9.0 / Linux 6.1

### ISSUE THREAD

**Issue by hoh** [aleph-im/aleph-vm#695]
**Is your feature request related to a problem? Please describe.**
[Firecracker v1.9.0 was released last week](https://github.com/firecracker-microvm/firecracker/releases/tag/v1.9.0).

It added official support for 6.1 microVM guest kernels.

According to an LLM:

> Linux 6.1 introduces several key features over 5.10, relevant for servers:
> 
> 1. **Long-Term Support (LTS)**: Linux 6.1 is an LTS release, like 5.10.
> 2. **Rust Integration**: Initial support for the Rust programming language for kernel development.
> 3. **BPF Enhancements**: Improved BPF (Berkeley Packet Filter) features, including dynamic pointer support and bpf_cpumap scaling.
> 4. **Security Improvements**: Kernel Control-Flow Integrity (kCFI), mitigations for retbleed, and improved Spectre/Meltdown mitigations.
> 5. **Filesystem Updates**: Significant performance and functionality improvements for EXT4, XFS, and Btrfs.
> 6. **Hardware Support**: Expanded support for ARM, RISC-V architectures, and improved Intel/AMD CPU optimizations.
> 7. **Energy Efficiency**: Enhanced power-saving features, particularly with newer CPUs.
> 8. **Virtualization**: Improved KVM (Kernel-based Virtual Machine) support for AMD and Intel processors, including nested virtualization enhancements.

**Describe the solution you'd like**

Upgrade the version of Firecracker run by `aleph-vm` to 1.9.0.
Upgrade the kernel used in virtual machines to 6.1 (I don't get why it's such an old kernel, we are at 6.10...).

**Comment by Psycojoker** [comment]
Migrated here https://aleph-im.atlassian.net/browse/ALEPH-125
